# yaml-language-server: $schema=../../schemas/yaml/services_schema.yaml
# Describes the format for available services for ha_aftership

add_package:
  #description: Add a package to AfterShip for tracking.
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: ha_aftership
    tracking_number:
      #description: The tracking number to add.
      #example: "1Z999AA10123456784"
      required: true
      selector:
        text:
    title:
      #description: The title for the tracking number.
      #example: "My Package"
      required: false
      selector:
        text:
    courier:
      #description: The courier code for the tracking number.
      #example: "USPS"
      required: false
      selector:
        text:

remove_package:
  #description: Remove a tracking number from AfterShip.
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: ha_aftership
    tracking_number:
      #description: The tracking number to remove.
      #example: "1Z999AA10123456784"
      required: true
      selector:
        text:

#update_tracking:
#  description: Update a tracking number in AfterShip.
#  fields:
#    tracking_number:
#      description: The tracking number to update.
#      example: "1Z999AA10123456784"
#      required: true
